### ISSUE TITLE
bug breaking block reference

### ISSUE THREAD

**Issue by nicolasmarc1** [liamcain/obsidian-creases#21] opened 2022-03-28 16:01 UTC
Hi, 

adding creases on sections that end with a block-id reference should add creases before (and not after) the block id, otherwise the block-id won't work anymore and the block reference break.

Thanks!

**Comment by liamcain** [comment] 2022-03-29 00:50
Good catch, I hadn't considered that. Will make a fix!

**Comment by liamcain** [comment] 2022-04-16 18:51
This should be fixed in v0.6.4

**Comment by nicolasmarc1** [comment] 2022-05-15 18:04
Hi! So i tried with the last version 0.6.4, but the problem seems to be the same, it add creases after the block id, is this working for you? Thanks!

**Comment by liamcain** [comment] 2022-05-15 18:28
Strange, this is the behavior I'm seeing:
https://user-images.githubusercontent.com/693981/168488113-77303a0e-6f60-42ed-9aa0-d3cbd7f222a0.mov

If there's additional steps for how to reproduce the issue, let me know!

**Comment by nicolasmarc1** [comment] 2022-05-17 17:00
> Strange, this is the behavior I'm seeing:
> 
>  Screen.Recording.2022-05-15.at.2.25.12.PM.mov 
> If there's additional steps for how to reproduce the issue, let me know!

Hi, thanks for the quick reply! This is weird, but doing the same things with the last version doesn't seem to work, not sure why. Here's the video demo:

https://user-images.githubusercontent.com/51007222/168869878-52cf4c5b-75b4-41a2-a5bc-974e7131c039.mp4

**Comment by liamcain** [comment] 2022-05-17 19:09
Thanks for the screen recording! I reopened the issue and will take another look, it might have something to do with the different commands (`toggle crease` vs `crease current folds`)

**Comment by nicolasmarc1** [comment] 2022-05-20 08:18
Yes i think you are right as "Toggle Crease" works for me! I mostly use 'crease current folds" to match with all obsidian folds

**Comment by danrthompson** [comment] 2022-09-23 19:22
I can confirm, the issue is in fact with `crease current folds`. `toggle creases` works perfectly. hopefully that should make it a relatively simple fix, if its easy to just use the logic from toggle creases.

if I have time ill take a look myself although id put it at a 20% that I end up fixing it - I have no experience developing obsidian plugins and if it takes too long to get it set up and working locally, and then to figure out the structure of plugins in general ill have to stop.

**Comment by nicolasmarc1** [comment] 2022-09-23 19:25
> I can confirm, the issue is in fact with `crease current folds`. `toggle creases` works perfectly. hopefully that should make it a relatively simple fix, if its easy to just use the logic from toggle creases.
> 
> if I have time ill take a look myself although id put it at a 20% that I end up fixing it - I have no experience developing obsidian plugins and if it takes too long to get it set up and working locally, and then to figure out the structure of plugins in general ill have to stop.

Hi, i already made a pull request today with a fix, hopefully it gets accepted soon

**Comment by danrthompson** [comment] 2022-09-23 20:40
OK great! Thanks very much for letting me know before I jumped in!

**Closed** 2022-10-10 19:05 UTC
Labels: bug

**Comment by nicolasmarc1** [comment] 2022-10-19 16:40
Hello @liamcain, any plans for a release with that fix ? thanks!

**Comment by nicolasmarc1** [comment] 2022-12-28 20:48
Hello @liamcain, any plans for a release with that fix ? thanks!

**Comment by liamcain** [comment] 2022-12-29 16:45
Thanks for bumping this @nicolasmarc1. Sorry for the long wait. I just released v0.6.6 with the fix.
